name: Deploy React App to IPFS via Pinata

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build React App
      run: |
        npm install
        npm run build

    - name: Archive Production Build
      run: |
        zip -r build.zip build/

    - name: Deploy to Pinata
      run: |
        curl -X POST https://api.pinata.cloud/pinning/pinFileToIPFS \
        -H "Content-Type: multipart/form-data" \
        -H "pinata_api_key: ${{ secrets.PINATA_API_KEY }}" \
        -H "pinata_secret_api_key: ${{ secrets.PINATA_SECRET_API_KEY }}" \
        -F "file=@build.zip"
